//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectolibreriaOF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public libro()
        {
            this.inventario = new HashSet<inventario>();
            this.ventas = new HashSet<ventas>();
        }
    
        public int id_libro { get; set; }
        public string nom_libro { get; set; }
        public string autor { get; set; }
        public string genero { get; set; }
        public string editorial { get; set; }
        public string edicion { get; set; }
        public Nullable<int> año { get; set; }
        public string idioma { get; set; }
        public Nullable<int> paginas { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string sipnosis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario> inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
