//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectolibreriaOF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int id_compra { get; set; }
        public int id_cliente { get; set; }
        public int id_libro { get; set; }
        public int id_inventario { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual inventario inventario { get; set; }
        public virtual libro libro { get; set; }
    }
}
